apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: commercial
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: argo-definitions/commercial
    repoURL: https://github.com/shivambawane27/argocd-test
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
