apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-dev
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: default
    name: in-cluster
  source:
    path: definitions/proj
    repoURL: https://github.com/shivambawane27/argocd-test
    targetRevision: HEAD