apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-dev-prooj-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: default
    name: in-cluster
  source:
    path: infra/core/proj-1/values-dev.yaml
    repoURL: https://github.com/shivambawane27/argocd-test
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
